# Generated by Django 5.1.4 on 2026-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_wishlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="last_reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultimo reminder inviato il"
            ),
        ),
    ]
