# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('code', models.CharField(help_text="Es. 'BLOCCO-B12-B13', 'ISLAND-CENTER'", max_length=50, verbose_name='Codice blocco')),
                ('name', models.CharField(blank=True, help_text="Es. 'Area Premium Centrale'", max_length=255, verbose_name='Nome commerciale')),
                ('block_type', models.CharField(blank=True, help_text='Es. double_corner, island_combined, linear_pair', max_length=50, verbose_name='Tipo blocco')),
                ('total_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Area totale (mq)')),
                ('block_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo del blocco venduto insieme (può differire dalla somma stand)', max_digits=10, null=True, verbose_name='Prezzo blocco')),
                ('status', models.CharField(choices=[('available', 'Disponibile'), ('reserved', 'Riservato'), ('assigned', 'Assegnato'), ('unavailable', 'Non disponibile')], default='available', max_length=20, verbose_name='Stato')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_blocks', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Blocco stand',
                'verbose_name_plural': 'Blocchi stand',
                'ordering': ['event', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('code', models.CharField(help_text="Es. 'B12'", max_length=20, verbose_name='Codice')),
                ('width_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Larghezza (m)')),
                ('depth_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Profondità (m)')),
                ('stand_type', models.CharField(blank=True, help_text='Es. corner_premium, linear, island, custom', max_length=50, verbose_name='Tipologia')),
                ('has_power', models.BooleanField(default=False, verbose_name='Allaccio elettrico')),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Potenza (kW)')),
                ('has_water', models.BooleanField(default=False, verbose_name='Allaccio idrico')),
                ('has_internet', models.BooleanField(default=False, verbose_name='Internet')),
                ('max_height_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altezza max (m)')),
                ('map_x', models.IntegerField(blank=True, null=True, verbose_name='Coord. X')),
                ('map_y', models.IntegerField(blank=True, null=True, verbose_name='Coord. Y')),
                ('status', models.CharField(choices=[('available', 'Disponibile'), ('reserved', 'Riservato'), ('assigned', 'Assegnato'), ('unavailable', 'Non disponibile')], default='available', max_length=20, verbose_name='Stato')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo base')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands', to='events.event', verbose_name='Evento')),
                ('stand_block', models.ForeignKey(blank=True, help_text='Se appartiene a un blocco di stand venduti insieme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stands', to='venues.standblock', verbose_name='Blocco')),
            ],
            options={
                'verbose_name': 'Stand',
                'verbose_name_plural': 'Stand',
                'ordering': ['event', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='standblock',
            index=models.Index(fields=['status'], name='venues_stan_status_b44c48_idx'),
        ),
        migrations.AddConstraint(
            model_name='standblock',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='stand_block_code_unique_per_event'),
        ),
        migrations.AddIndex(
            model_name='stand',
            index=models.Index(fields=['status'], name='venues_stan_status_a956ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='stand',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='stand_code_unique_per_event'),
        ),
    ]
