# Generated by Django 5.1.4 on 2026-06-11 22:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_stand_quote_description_bilingue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stand",
            options={
                "ordering": [
                    "event",
                    models.OrderBy(django.db.models.functions.text.Length("code")),
                    "code",
                ],
                "verbose_name": "Stand",
                "verbose_name_plural": "Stand",
            },
        ),
        migrations.AlterModelOptions(
            name="standblock",
            options={
                "ordering": [
                    "event",
                    models.OrderBy(django.db.models.functions.text.Length("code")),
                    "code",
                ],
                "verbose_name": "Blocco stand",
                "verbose_name_plural": "Blocchi stand",
            },
        ),
    ]
