# Generated by Django 5.1.4 on 2026-06-11 23:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0004_alter_stand_options_alter_standblock_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modificato il")),
                (
                    "name",
                    models.CharField(
                        help_text="Es. desk, stand, area nuda, premium. Compare nel menu a tendina degli stand.",
                        max_length=50,
                        unique=True,
                        verbose_name="Tipologia",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Attiva")),
                ("display_order", models.IntegerField(default=0, verbose_name="Ordine")),
            ],
            options={
                "verbose_name": "Tipologia stand",
                "verbose_name_plural": "Tipologie stand",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
