# Generated by Django 5.1.4 on 2026-08-26 17:46

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0006_seed_standtype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stand",
            options={
                "ordering": [
                    "event",
                    models.OrderBy(
                        models.Func(
                            models.F("code"),
                            models.Value("\\d.*$"),
                            models.Value(""),
                            function="REGEXP_REPLACE",
                        )
                    ),
                    models.OrderBy(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.comparison.NullIf(
                                models.Func(
                                    models.F("code"),
                                    models.Value("\\D"),
                                    models.Value(""),
                                    models.Value("g"),
                                    function="REGEXP_REPLACE",
                                ),
                                models.Value(""),
                            ),
                            models.IntegerField(),
                        )
                    ),
                    "code",
                ],
                "verbose_name": "Stand",
                "verbose_name_plural": "Stand",
            },
        ),
        migrations.AlterModelOptions(
            name="standblock",
            options={
                "ordering": [
                    "event",
                    models.OrderBy(
                        models.Func(
                            models.F("code"),
                            models.Value("\\d.*$"),
                            models.Value(""),
                            function="REGEXP_REPLACE",
                        )
                    ),
                    models.OrderBy(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.comparison.NullIf(
                                models.Func(
                                    models.F("code"),
                                    models.Value("\\D"),
                                    models.Value(""),
                                    models.Value("g"),
                                    function="REGEXP_REPLACE",
                                ),
                                models.Value(""),
                            ),
                            models.IntegerField(),
                        )
                    ),
                    "code",
                ],
                "verbose_name": "Blocco stand",
                "verbose_name_plural": "Blocchi stand",
            },
        ),
        migrations.AddField(
            model_name="stand",
            name="sponsor_notes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Indicazioni per il cliente (es. specifiche per le grafiche): compaiono nel PREVENTIVO e nel CONTRATTO/domanda di ammissione. L'inglese si compila da solo al salvataggio.",
                verbose_name="Note per lo sponsor (IT/EN)",
            ),
        ),
        migrations.AddField(
            model_name="standblock",
            name="sponsor_notes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Indicazioni per il cliente (es. specifiche per le grafiche): compaiono nel PREVENTIVO e nel CONTRATTO/domanda di ammissione. L'inglese si compila da solo al salvataggio.",
                verbose_name="Note per lo sponsor (IT/EN)",
            ),
        ),
    ]
