# Generated by Django 5.1.4 on 2026-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_alter_stand_options_alter_standblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='access_door',
            field=models.CharField(blank=True, help_text="Numero o nome dell'accesso da usare per montaggio e smontaggio (es. 3). Compare nel Regolamento tecnico (Allegato 2) del contratto.", max_length=50, verbose_name='Porta di accesso al padiglione'),
        ),
    ]
