# Generated by Django 5.1.4 on 2026-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_stand_access_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='caratteristiche',
            field=models.TextField(blank=True, help_text='Tutto quello che lo Sponsor deve sapere oltre a misure, altezza, kW, acqua e internet (es. lati liberi, pavimentazione, pilastri, carico ammesso). Compare nel Regolamento tecnico e nel PASS allestimento.', verbose_name='Altre caratteristiche dello spazio'),
        ),
    ]
