# Generated by Django 5.1.4 on 2026-09-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_stand_caratteristiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='caratteristiche',
            field=models.TextField(blank=True, help_text='Note tecniche su questo spazio (es. lati liberi, pilastri, vincoli di allestimento). Compaiono sotto il RIEPILOGO TECNICO DELLO SPAZIO nella Domanda di ammissione (Allegato 1), nel Regolamento tecnico (Allegato 2) e nel PASS allestimento.', verbose_name='Indicazioni specifiche'),
        ),
    ]
