# Generated by Django 5.1.4 on 2026-06-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_aifa_reference_event_medtech_svc_reference'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_events',
            field=models.ManyToManyField(blank=True, help_text="Eventi che questo utente puo' gestire (contratti, scadenze, pagamenti, eventi, stand). Vuoto = nessun evento. Amministratori e superuser vedono tutto.", related_name='managers', to='events.event', verbose_name='Eventi abilitati'),
        ),
    ]
