# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.contrib.postgres.fields
import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('slug', models.SlugField(help_text="Identificatore breve per URL, es. 'ferrara-cardio-2026'", max_length=100, unique=True, verbose_name='Slug')),
                ('name', models.JSONField(help_text='Formato: {"it": "...", "en": "..."}', verbose_name='Nome (multilingua)')),
                ('description', models.JSONField(blank=True, help_text='Formato: {"it": "...", "en": "..."}', null=True, verbose_name='Descrizione (multilingua)')),
                ('event_type', models.CharField(choices=[('ECM', 'ECM'), ('NON_ECM', 'Non ECM')], max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Data inizio')),
                ('end_date', models.DateField(verbose_name='Data fine')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Sede')),
                ('venue_address', models.CharField(blank=True, help_text="Indirizzo completo della venue (es. 'Centro Congressi, Via Roma 1, Bologna')", max_length=500, verbose_name='Indirizzo completo sede')),
                ('status', models.CharField(choices=[('planning', 'In pianificazione'), ('selling', 'Vendita aperta'), ('closed_sales', 'Vendita chiusa'), ('live', 'In corso'), ('archived', 'Archiviato')], default='planning', max_length=20, verbose_name='Stato')),
                ('ecm_id', models.CharField(blank=True, help_text="Solo per eventi ECM (es. '1328')", max_length=20, verbose_name='ID accreditamento Agenas')),
                ('scientific_director', models.CharField(blank=True, help_text="Nome completo, es. 'Prof. Mario Rossi'", max_length=200, verbose_name='Responsabile scientifico')),
                ('organizer_legal_name', models.CharField(blank=True, help_text='La tua ragione sociale, usata nei contratti', max_length=255, verbose_name='Ragione sociale organizzatore')),
                ('contract_signing_location', models.CharField(blank=True, max_length=255, verbose_name='Luogo firma contratti')),
                ('notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('supported_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('it', 'Italiano'), ('en', 'English')], max_length=2), default=events.models.default_supported_languages, help_text='Almeno una. Determina cosa gli sponsor vedono nel portale.', size=None, verbose_name='Lingue supportate')),
                ('default_language', models.CharField(choices=[('it', 'Italiano'), ('en', 'English')], default='it', max_length=2, verbose_name='Lingua di default')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status'], name='events_even_status_5709b6_idx'), models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx')],
            },
        ),
    ]
