# Generated by Django 5.1.4 on 2026-05-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(blank=True, help_text="Sigla breve per i numeri di contratto, es. 'HIFU'. Se vuota, viene generata automaticamente.", max_length=12, verbose_name='Sigla evento'),
        ),
    ]
