# Generated by Django 5.1.4 on 2026-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_header_image',
            field=models.FileField(blank=True, help_text='Immagine mostrata in cima alle email di questo evento, a tutta larghezza (max 600px). Consigliato PNG/JPG.', null=True, upload_to='events/email_headers/', verbose_name='Header email congresso'),
        ),
    ]
