# Generated by Django 5.1.4 on 2026-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_email_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aifa_reference',
            field=models.CharField(blank=True, help_text='Solo per archivio/consultazione interna.', max_length=100, verbose_name='Numero riferimento AIFA'),
        ),
        migrations.AddField(
            model_name='event',
            name='medtech_svc_reference',
            field=models.CharField(blank=True, help_text='Solo per archivio/consultazione interna.', max_length=100, verbose_name='Numero riferimento MEDTECH/SVC'),
        ),
    ]
