# Generated by Django 5.1.4 on 2026-06-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_aifa_reference_event_medtech_svc_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, help_text="Es. 'Palazzo dei Congressi di Bologna' (usato nei documenti).", max_length=255, verbose_name='Nome sede'),
        ),
    ]
