# Generated by Django 5.1.4 on 2026-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_venue_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="scientific_secretariat",
            field=models.TextField(
                blank=True,
                help_text="Testo libero con tutti i dati della segreteria scientifica (nome, indirizzo, contatti...). Appare in basso a destra nel PDF del preventivo. Lascia vuoto per non mostrarla.",
                verbose_name="Segreteria Scientifica (dati per il preventivo)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="scientific_secretariat_logo",
            field=models.FileField(
                blank=True,
                help_text="Logo mostrato accanto ai dati della segreteria scientifica nel PDF del preventivo (consigliato PNG/JPG).",
                null=True,
                upload_to="events/scientific_secretariat/",
                verbose_name="Logo Segreteria Scientifica",
            ),
        ),
    ]
