# Generated by Django 5.1.4 on 2026-07-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_scientific_secretariat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancellation_penalty_percent",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Percentuale dell'importo totale trattenuta come penale in caso di rinuncia entro 30 gg. Appare nei Termini di cancellazione del contratto.",
                verbose_name="Penale cancellazione (%)",
            ),
        ),
    ]
