# Generated by Django 5.1.4 on 2026-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_penale_cancellazione"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="notification_cc_emails",
            field=models.TextField(
                blank=True,
                help_text="Indirizzi a cui inoltrare in copia (BCC) tutte le email inviate per questo evento. Uno per riga oppure separati da virgola. Lo sponsor non li vede.",
                verbose_name="Email in copia (inoltro automatico)",
            ),
        ),
    ]
