# Generated by Django 5.1.4 on 2026-07-09 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_notification_cc_emails"),
        ("sponsors", "0018_sponsor_is_pharma_company_sponsor_sis_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionalCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modificato il")),
                (
                    "name",
                    models.CharField(
                        help_text="Solo per riconoscerla in lista: il cliente non la vede.",
                        max_length=255,
                        verbose_name="Nome interno",
                    ),
                ),
                (
                    "subject",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bilingue IT/EN.",
                        verbose_name="Oggetto",
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bilingue IT/EN. Segnaposto: {{ sponsor.legal_name }}, {{ event_name }}, {{ contact.full_name }}.",
                        verbose_name="Corpo email",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        default=14,
                        help_text="Intervallo minimo tra un invio e il successivo.",
                        verbose_name="Ogni quanti giorni",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Attiva")),
                (
                    "last_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ultimo invio"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotional_campaigns",
                        to="events.event",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagna promozionale",
                "verbose_name_plural": "Campagne promozionali",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionalCampaignOptOut",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modificato il")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opt_outs",
                        to="events.promotionalcampaign",
                        verbose_name="Campagna",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_opt_outs",
                        to="sponsors.contact",
                        verbose_name="Contatto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disiscrizione campagna",
                "verbose_name_plural": "Disiscrizioni campagne",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "contact"),
                        name="unique_promocampaign_optout_campaign_contact",
                    )
                ],
            },
        ),
    ]
