# Generated by Django 5.1.4 on 2026-08-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_promotionalcampaign_promotionalcampaignoptout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organizer_legal_name",
            field=models.CharField(
                blank=True,
                help_text="Compila SOLO se l'organizzatore di questo evento non è VALET: il nome inserito sostituisce la ragione sociale nei PDF (contratto, domanda di ammissione). Se lasci vuoto viene usata la dicitura standard VALET. Attenzione: cambia solo il nome — sede, P.IVA e rappresentante nei documenti restano quelli VALET.",
                max_length=255,
                verbose_name="Ragione sociale organizzatore",
            ),
        ),
    ]
