# Generated by Django 5.1.4 on 2026-09-25 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_organizer_legal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSetupDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('kind', models.CharField(choices=[('allestimento', 'Allestimento'), ('disallestimento', 'Disallestimento')], default='allestimento', max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Orario di inizio')),
                ('end_time', models.TimeField(verbose_name='Orario di fine')),
                ('notes', models.CharField(blank=True, help_text="Facoltativo, es. 'solo stand preallestiti', 'ingresso carico merci'.", max_length=255, verbose_name='Note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_days', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Giorno di allestimento/disallestimento',
                'verbose_name_plural': 'Allestimento e disallestimento',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
