# Generated by Django 5.1.4 on 2026-09-25 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventsetupday'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contract_annex_enabled',
            field=models.BooleanField(default=False, help_text="Se spuntato, il file qui sotto viene aggiunto come ALLEGATO 2 in fondo al contratto di sponsorizzazione (dopo la Domanda di ammissione, che e' l'Allegato 1).", verbose_name='Inserisci allegato al contratto'),
        ),
        migrations.AddField(
            model_name='event',
            name='contract_annex_file',
            field=models.FileField(blank=True, help_text='Il Word viene convertito in PDF alla generazione di ogni contratto. I vecchi file .doc vanno prima salvati come .docx.', null=True, upload_to='events/contract_annex/', validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf'])], verbose_name="File dell'allegato (Word .docx o PDF)"),
        ),
        migrations.AddField(
            model_name='event',
            name='contract_annex_title',
            field=models.CharField(blank=True, default='Regolamento tecnico', help_text="Stampato in testa all'allegato: «ALLEGATO 2 – <titolo>».", max_length=120, verbose_name="Titolo dell'allegato"),
        ),
    ]
