# Generated by Django 5.1.4 on 2026-09-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_contract_annex_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='magazzino_dettagli',
            field=models.TextField(blank=True, help_text="Es. giorni e orari di ricevimento, referente, indicazioni per il corriere. Compare nel Regolamento tecnico sotto l'indirizzo del magazzino.", verbose_name='Giorni, orari e indicazioni per la consegna'),
        ),
        migrations.AddField(
            model_name='event',
            name='magazzino_indirizzo',
            field=models.TextField(blank=True, help_text='Dove gli Sponsor spediscono i materiali per lo stand. Compare nel Regolamento tecnico (Allegato 2) alla voce INDIRIZZO.', verbose_name='Indirizzo del magazzino di consegna'),
        ),
    ]
