# Generated by Django 5.1.4 on 2026-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_magazzino_dettagli_event_magazzino_indirizzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='montaggio_dettagli',
            field=models.TextField(blank=True, help_text='Facoltativo, es. lunghezza massima dei mezzi, varco, parcheggio, documenti da esibire.', verbose_name="Indicazioni per l'accesso al montaggio"),
        ),
        migrations.AddField(
            model_name='event',
            name='montaggio_indirizzo',
            field=models.TextField(blank=True, help_text="Da dove entrano Sponsor e allestitori coi mezzi, se diverso dall'ingresso del congresso (es. «Via Calzoni 1/5 - Bologna»). Compare nel Regolamento tecnico e nella mail del PASS allestimento.", verbose_name='Indirizzo di accesso per montaggio e smontaggio'),
        ),
    ]
