# Generated by Django 5.1.4 on 2026-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_montaggio_dettagli_event_montaggio_indirizzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='magazzino_ritiro',
            field=models.TextField(blank=True, help_text='Istruzioni, orari e obblighi per ritirare il materiale a fine evento. Compaiono nella mail del PASS allestimento e nel suo PDF (nel Regolamento tecnico con il segnaposto {{ magazzino_ritiro }}).', verbose_name='Ritiro del materiale a fine evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='regole_montaggio',
            field=models.TextField(blank=True, help_text='Compaiono nella mail del PASS allestimento e nel suo PDF (nel Regolamento tecnico con il segnaposto {{ regole_montaggio }}).', verbose_name="Regole per il montaggio e lo smontaggio dell'area espositiva"),
        ),
    ]
