# Generated by Django 5.1.4 on 2026-09-26 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_magazzino_ritiro_event_regole_montaggio'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contract_annex_moduli',
            field=models.FileField(blank=True, help_text="Es. i moduli ME1/ME2 del Polo Congressuale: vengono accodati cosi' come sono in fondo all'Allegato 2 e contati nelle sue pagine.", null=True, upload_to='events/contract_annex/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name="Moduli da allegare in fondo all'Allegato 2 (PDF)"),
        ),
    ]
