# Generated by Django 5.1.4 on 2026-09-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_contract_annex_moduli'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='referente_sponsor',
            field=models.TextField(blank=True, help_text='Es. «Elisa Fantini Tel. ... – WhatsApp ... - email». Compare evidenziato nella mail del PASS allestimento e nel suo PDF.', verbose_name='Referente per informazioni Sponsor'),
        ),
    ]
