# Generated by Django 5.1.4 on 2026-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome segreteria')),
                ('address', models.TextField(blank=True, verbose_name='Indirizzo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='Sito internet')),
                ('vat_number', models.CharField(blank=True, max_length=30, verbose_name='P.IVA')),
                ('rea', models.CharField(blank=True, max_length=30, verbose_name='REA')),
                ('logo', models.FileField(blank=True, help_text='Logo mostrato nel footer delle email.', null=True, upload_to='organizer/', verbose_name='Logo segreteria')),
            ],
            options={
                'verbose_name': 'Impostazioni segreteria',
                'verbose_name_plural': 'Impostazioni segreteria',
            },
        ),
    ]
