# Generated by Django 5.1.4 on 2026-06-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_payment_terms_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizersettings",
            name="messages_notify_email",
            field=models.EmailField(
                blank=True,
                help_text="Indirizzo a cui inviare un avviso quando un cliente risponde a un messaggio nel portale. Vuoto = usa l'email della segreteria.",
                max_length=254,
                verbose_name="Email notifiche risposte portale",
            ),
        ),
    ]
