# Generated by Django 5.1.4 on 2026-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_organizersettings_messages_notify_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizersettings",
            name="privacy_policy",
            field=models.TextField(
                blank=True,
                help_text="Testo dell'informativa mostrato nel portale. Vuoto = testo segnaposto. Consigliato farlo validare da un consulente.",
                verbose_name="Informativa privacy (testo)",
            ),
        ),
        migrations.AddField(
            model_name="organizersettings",
            name="privacy_policy_version",
            field=models.CharField(
                default="1.0",
                help_text="Cambia la versione quando aggiorni l'informativa: ai clienti verrà richiesta di nuovo l'accettazione al prossimo accesso.",
                max_length=20,
                verbose_name="Versione informativa",
            ),
        ),
    ]
