# Generated by Django 5.1.4 on 2026-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_organizersettings_privacy_policy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Se attivo, le email vengono inviate con i dati qui sotto. Se disattivo, si usano i dati di sistema (.env).",
                        verbose_name="Usa questa configurazione SMTP",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="Es. smtp.gmail.com, smtp.aruba.it, ...",
                        max_length=200,
                        verbose_name="Server SMTP (host)",
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        default=587, help_text="587 (TLS) oppure 465 (SSL).", verbose_name="Porta"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Di solito l'indirizzo email completo.",
                        max_length=200,
                        verbose_name="Utente",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Password della casella o password per app (es. Gmail).",
                        max_length=255,
                        verbose_name="Password",
                    ),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="Usa TLS (porta 587)")),
                ("use_ssl", models.BooleanField(default=False, verbose_name="Usa SSL (porta 465)")),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        help_text="Indirizzo che appare come mittente. Vuoto = usa l'utente.",
                        max_length=254,
                        verbose_name="Mittente (from)",
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True,
                        help_text="Es. «Segreteria VALET». Opzionale.",
                        max_length=120,
                        verbose_name="Nome mittente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione email (SMTP)",
                "verbose_name_plural": "Configurazione email (SMTP)",
            },
        ),
    ]
