# Generated by Django 5.1.4 on 2026-06-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_emailsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizersettings",
            name="privacy_short_en",
            field=models.TextField(
                blank=True,
                help_text="Versione inglese della descrizione breve. Vuoto = usa l'italiano.",
                verbose_name="Descrizione breve (EN)",
            ),
        ),
        migrations.AddField(
            model_name="organizersettings",
            name="privacy_short_it",
            field=models.TextField(
                blank=True,
                help_text="Testo breve mostrato nella pagina di consenso del portale (italiano). Il testo completo è sul sito.",
                verbose_name="Descrizione breve (IT)",
            ),
        ),
    ]
