# Generated by Django 5.1.4 on 2026-06-09 07:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_organizersettings_privacy_short_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizersettings",
            name="messages_notify_email",
            field=models.CharField(
                blank=True,
                help_text="Uno o più indirizzi separati da ; (o ,) a cui inviare l'avviso quando un cliente risponde a un messaggio nel portale. Vuoto = usa l'email della segreteria.",
                max_length=500,
                validators=[core.models._validate_email_list],
                verbose_name="Email notifiche risposte portale",
            ),
        ),
    ]
