# Generated by Django 5.1.4 on 2026-06-09 07:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_organizersettings_messages_notify_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizersettings",
            name="email",
            field=models.CharField(
                blank=True,
                help_text="Uno o più indirizzi separati da ; (o ,).",
                max_length=500,
                validators=[core.models._validate_email_list],
                verbose_name="Email",
            ),
        ),
    ]
