# Generated by Django 5.1.4 on 2026-06-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_organizersettings_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsettings",
            name="test_recipient",
            field=models.EmailField(
                blank=True,
                help_text="Indirizzo a cui inviare l'email di PROVA. Vuoto = la tua email di accesso.",
                max_length=254,
                verbose_name="Email per il test",
            ),
        ),
    ]
