# Generated by Django 5.1.4 on 2026-10-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_emailsettings_test_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsettings",
            name="pausa_campagne_secondi",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Quanto aspettare fra un'email e la successiva quando parte una campagna. Serve a non spedire una raffica: il server di posta può limitare gli invii, e una raffica improvvisa è uno dei segnali che i filtri antispam guardano. 4-5 secondi per poche decine di destinatari, 15-30 per qualche centinaio. 0 = nessuna pausa. Massimo 60. Con 300 destinatari e 15 secondi la campagna dura circa un'ora e un quarto: parte in background, puoi chiudere la pagina. Su liste molto lunghe la pausa viene ridotta da sola, perché una campagna non può durare più di quattro ore: meglio spedire più in fretta del voluto che perdere per strada la coda della lista.",
                verbose_name="Pausa fra gli invii delle campagne (secondi)",
            ),
        ),
    ]
