# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('status', models.CharField(choices=[('active', 'Attivo'), ('abandoned', 'Abbandonato'), ('completed', 'Completato'), ('expired', 'Scaduto')], default='active', max_length=20, verbose_name='Stato')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima attività')),
                ('abandoned_email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email abbandono inviata')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sessione carrello',
                'verbose_name_plural': 'Sessioni carrello',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancellato il')),
                ('contract_kind', models.CharField(choices=[('main', 'Principale'), ('addon', 'Addon ecommerce'), ('addendum', 'Addendum')], default='main', max_length=20, verbose_name='Tipo contratto')),
                ('origin', models.CharField(choices=[('manual', 'Manuale'), ('ecommerce', 'Ecommerce'), ('import', 'Importato')], default='manual', max_length=20, verbose_name='Origine')),
                ('language', models.CharField(default='it', max_length=2, verbose_name='Lingua')),
                ('contract_number', models.CharField(help_text="Generato dall'app, formato es. '2026-FE-001'", max_length=50, unique=True, verbose_name='Numero contratto')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('sent', 'Inviato'), ('pending_payment', 'In attesa pagamento'), ('signed', 'Firmato'), ('active', 'Attivo'), ('completed', 'Completato'), ('cancelled', 'Annullato')], default='draft', max_length=20, verbose_name='Stato')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Data emissione')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Inviato il')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Data firma')),
                ('cancelled_date', models.DateTimeField(blank=True, null=True, verbose_name='Annullato il')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo annullamento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Imponibile')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Totale')),
                ('payment_method', models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bonifico'), ('installments', 'Rateale'), ('other', 'Altro')], max_length=50, verbose_name='Modalità pagamento')),
                ('payment_terms', models.CharField(blank=True, help_text="Es. '30 gg data fattura'", max_length=100, verbose_name='Termini pagamento')),
                ('payment_installments', models.IntegerField(default=1, verbose_name='Numero rate')),
                ('vat_applicable', models.BooleanField(default=True, verbose_name='IVA applicabile')),
                ('vat_exemption_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo esenzione IVA')),
                ('template_used', models.CharField(blank=True, help_text='Es. ECM_2026, NON_ECM_2026, CUSTOM', max_length=50, verbose_name='Template usato')),
                ('special_clauses', models.TextField(blank=True, verbose_name='Clausole speciali')),
                ('internal_notes', models.TextField(blank=True, help_text='Non vanno nel PDF, solo per il team', verbose_name='Note interne')),
            ],
            options={
                'verbose_name': 'Contratto',
                'verbose_name_plural': 'Contratti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('service_name_snapshot', models.CharField(max_length=255, verbose_name='Nome servizio')),
                ('service_description_snapshot', models.TextField(blank=True, verbose_name='Descrizione')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo unitario')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Sconto %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sconto importo')),
                ('line_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Imponibile riga')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=4, verbose_name='IVA %')),
                ('line_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IVA riga')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale riga')),
                ('notes', models.TextField(blank=True, verbose_name='Note riga')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Riga contratto',
                'verbose_name_plural': 'Righe contratto',
                'ordering': ['contract', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deadline_type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('due_date', models.DateField(verbose_name='Data scadenza')),
                ('status', models.CharField(choices=[('pending', 'Da fare'), ('reminder_sent', 'Reminder inviato'), ('received', 'Ricevuto'), ('overdue', 'In ritardo'), ('waived', 'Annullata')], default='pending', max_length=20, verbose_name='Stato')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completata il')),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0, verbose_name='N. reminder inviati')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Scadenza',
                'verbose_name_plural': 'Scadenze',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bonifico'), ('manual', 'Manuale')], max_length=20, verbose_name='Metodo')),
                ('amount_gross', models.DecimalField(decimal_places=2, help_text='Totale pagato dal cliente', max_digits=10, verbose_name='Importo lordo')),
                ('amount_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commissione PayPal o costi bonifico', max_digits=10, verbose_name='Commissione')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In elaborazione'), ('succeeded', 'Completato'), ('failed', 'Fallito'), ('refunded', 'Rimborsato'), ('partial_refund', 'Rimborso parziale')], default='pending', max_length=20, verbose_name='Stato')),
                ('paypal_order_id', models.CharField(blank=True, max_length=100, verbose_name='PayPal order ID')),
                ('paypal_capture_id', models.CharField(blank=True, max_length=100, verbose_name='PayPal capture ID')),
                ('paypal_payer_email', models.EmailField(blank=True, max_length=254)),
                ('paypal_payer_id', models.CharField(blank=True, max_length=100)),
                ('paypal_response', models.JSONField(blank=True, null=True, verbose_name='PayPal raw response')),
                ('bank_transfer_reference', models.CharField(blank=True, help_text="Univoca, generata dall'app", max_length=100, verbose_name='Causale bonifico')),
                ('bank_transfer_received_at', models.DateField(blank=True, null=True, verbose_name='Data accredito')),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Avviato il')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('last_webhook_event_id', models.CharField(blank=True, help_text='Per idempotenza dei webhook PayPal', max_length=100, verbose_name='Ultimo webhook ID')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
                'ordering': ['-created_at'],
            },
        ),
    ]
