# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contracts', '0001_initial'),
        ('events', '0001_initial'),
        ('sponsors', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsession',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_sessions', to='sponsors.contact', verbose_name='Contatto'),
        ),
        migrations.AddField(
            model_name='contract',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='events.event', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, help_text='Per contratti addon, riferimento al main contract', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_contracts', to='contracts.contract', verbose_name='Contratto principale'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='sponsors.sponsor', verbose_name='Sponsor'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sponsor_signer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to='sponsors.contact', verbose_name='Firmatario'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='venues.stand', verbose_name='Stand singolo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stand_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='venues.standblock', verbose_name='Blocco stand'),
        ),
        migrations.AddField(
            model_name='cartsession',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_session', to='contracts.contract', verbose_name='Contratto bozza (carrello)'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.contract', verbose_name='Contratto'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='catalog.service', verbose_name='Servizio'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='completed_by_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deadlines', to='sponsors.contact', verbose_name='Completata da'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='contracts.contract', verbose_name='Contratto'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='contract_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to='contracts.contractline', verbose_name='Riga contratto'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='deadline_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.deadlinetemplate', verbose_name='Template'),
        ),
    ]
