# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_transfer_confirmed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Confermato da'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contracts.contract', verbose_name='Contratto'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_c_status_aa7a80_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='contracts_c_contrac_876f48_idx'),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['status'], name='contracts_c_status_ef43bd_idx'),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['last_activity_at'], name='contracts_c_last_ac_ce3439_idx'),
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['due_date'], name='contracts_d_due_dat_5923ca_idx'),
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['status', 'due_date'], name='contracts_d_status_b19193_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='contracts_p_status_3bb14a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paypal_order_id'], name='contracts_p_paypal__d8b297_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank_transfer_reference'], name='contracts_p_bank_tr_7cc6ea_idx'),
        ),
    ]
