# Generated by Django 5.1.4 on 2026-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='requires_aifa',
            field=models.BooleanField(default=False, verbose_name='Richiede AIFA (per questo evento)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='requires_svc_medtech',
            field=models.BooleanField(default=False, verbose_name='Richiede MEDTECH/SVC (per questo evento)'),
        ),
    ]
