# Generated by Django 5.1.4 on 2026-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_requires_aifa_contract_requires_svc_medtech'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='quote_intro_text',
            field=models.TextField(blank=True, help_text='Testo introduttivo della lettera di preventivo da inviare al cliente. Lasciare vuoto se non serve. Il sistema aggiunge intestazione e riepilogo dati.', verbose_name='Testo lettera preventivo'),
        ),
    ]
