# Generated by Django 5.1.4 on 2026-05-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_option_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lascia vuoto per usare il prezzo standard del servizio.', max_digits=10, null=True, verbose_name='Prezzo unitario'),
        ),
    ]
