# Generated by Django 5.1.4 on 2026-05-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contractline_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dati inviati dal cliente'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='content_schema',
            field=models.JSONField(blank=True, default=list, help_text='Definizione dei campi che il cliente deve compilare.', verbose_name='Campi richiesti'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='submission_kind',
            field=models.CharField(default='file', max_length=20, verbose_name='Tipo consegna'),
        ),
    ]
