# Generated by Django 5.1.4 on 2026-05-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_servicevariant'),
        ('contracts', '0012_deadline_content_data_deadline_content_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractline',
            name='service_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant_lines', to='catalog.servicevariant', verbose_name='Variante'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='variant_label_snapshot',
            field=models.CharField(blank=True, max_length=120, verbose_name='Variante (etichetta)'),
        ),
    ]
