# Generated by Django 5.1.4 on 2026-06-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0013_contractline_service_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadline",
            name="materials_reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Materiale visionato il"
            ),
        ),
    ]
