# Generated by Django 5.1.4 on 2026-07-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0014_deadline_materials_reviewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="stand_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sconto in valore applicato alla riga stand.",
                max_digits=10,
                null=True,
                verbose_name="Sconto stand (€)",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="stand_discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sconto percentuale (0-100) applicato alla riga stand.",
                max_digits=5,
                null=True,
                verbose_name="Sconto stand (%)",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="stand_price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Se valorizzato, sostituisce il prezzo base dello stand/blocco nella riga del contratto.",
                max_digits=10,
                null=True,
                verbose_name="Prezzo stand (override)",
            ),
        ),
    ]
