# Generated by Django 5.1.4 on 2026-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0016_alter_contract_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bonifico"),
                    ("installments", "Rateale"),
                    ("riba", "RI.BA."),
                    ("bb_scadenza_fissa", "Bonifico (B.B.) con scadenza fissa"),
                    ("other", "Altro"),
                ],
                max_length=50,
                verbose_name="Modalità pagamento",
            ),
        ),
    ]
