# Generated by Django 5.1.4 on 2026-07-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_deadline_template_physical_shipping"),
        ("contracts", "0017_alter_contract_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractline",
            name="custom_description",
            field=models.CharField(
                blank=True,
                help_text="Usata SOLO se 'Servizio' e' vuoto: diventa il nome della riga nel preventivo/contratto. Nessun controllo di quantita'/disponibilita' di catalogo si applica a queste righe.",
                max_length=255,
                verbose_name="Descrizione libera",
            ),
        ),
        migrations.AlterField(
            model_name="contractline",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Lascia vuoto per una RIGA LIBERA (richiesta specifica del cliente non a catalogo): compila invece 'Descrizione libera' qui sotto.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_lines",
                to="catalog.service",
                verbose_name="Servizio",
            ),
        ),
    ]
