# Generated by Django 5.1.4 on 2026-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0018_contractline_custom_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadline",
            name="file_area_label",
            field=models.CharField(
                blank=True,
                help_text="Testo mostrato dentro il riquadro di caricamento file nel portale. Vuoto = riquadro generico.",
                max_length=255,
                verbose_name="Etichetta area di caricamento",
            ),
        ),
    ]
