# Generated by Django 5.1.4 on 2026-09-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0019_deadline_file_area_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="customer_reference",
            field=models.CharField(
                blank=True,
                help_text="Riferimento che il CLIENTE chiede di riportare sui documenti: numero di ordine d'acquisto (PO), CIG, commessa. Se compilato viene stampato come 'Vostro riferimento: ...' su preventivo, contratto e domanda di ammissione. Lascialo vuoto per le aziende che non lo richiedono: in quel caso non compare nulla.",
                max_length=100,
                verbose_name="Vostro riferimento (PO)",
            ),
        ),
    ]
