# Generated by Django 5.1.4 on 2026-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_contract_deposit_amount_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pass_allestimento_inviato_il',
            field=models.DateTimeField(blank=True, editable=False, help_text="Data e ora dell'ultimo invio del PASS allestimento allo Sponsor.", null=True, verbose_name='PASS allestimento inviato il'),
        ),
    ]
