# Generated by Django 5.1.4 on 2026-09-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_contract_pass_allestimento_inviato_il'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractline',
            options={'ordering': ['contract', 'display_order', 'id'], 'verbose_name': 'Riga contratto', 'verbose_name_plural': 'Righe contratto'},
        ),
    ]
