# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Es. create, update, delete, status_change, login', max_length=50, verbose_name='Azione')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Tipo entità')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='ID entità')),
                ('changes', models.JSONField(blank=True, help_text='Es. {"status": {"from": "draft", "to": "sent"}}', null=True, verbose_name='Modifiche')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('object_id', models.UUIDField(verbose_name='ID entità')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Telefono'), ('meeting', 'Meeting'), ('note', 'Nota')], default='email', max_length=20, verbose_name='Canale')),
                ('communication_type', models.CharField(choices=[('initial_send', 'Invio iniziale contratto'), ('reminder', 'Reminder scadenza'), ('overdue_alert', 'Sollecito ritardo'), ('thank_you', 'Ringraziamento'), ('document_request', 'Richiesta documenti'), ('manual', 'Manuale')], max_length=50, verbose_name='Tipo')),
                ('recipients_to', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='Destinatari (To)')),
                ('recipients_cc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='Destinatari (CC)')),
                ('recipients_bcc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='Destinatari (BCC)')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Oggetto')),
                ('body_text', models.TextField(blank=True, verbose_name='Corpo testuale')),
                ('body_html', models.TextField(blank=True, verbose_name='Corpo HTML')),
                ('attachment_document_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='Allegati (Document IDs)')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('queued', 'In coda'), ('sent', 'Inviata'), ('delivered', 'Consegnata'), ('opened', 'Aperta'), ('clicked', 'Cliccata'), ('bounced', 'Bounced'), ('failed', 'Fallita')], default='queued', max_length=20, verbose_name='Stato')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='ID messaggio provider')),
                ('provider_response', models.JSONField(blank=True, null=True, verbose_name='Risposta provider')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Inviata il')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0, verbose_name='N. aperture')),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_reason', models.TextField(blank=True)),
                ('is_automated', models.BooleanField(default=False, help_text='True se inviata da automazione, False se manuale', verbose_name='Automatica')),
            ],
            options={
                'verbose_name': 'Comunicazione',
                'verbose_name_plural': 'Comunicazioni',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('object_id', models.UUIDField(verbose_name='ID entità')),
                ('document_type', models.CharField(choices=[('contract_pdf', 'Contratto PDF'), ('signed_contract', 'Contratto firmato'), ('invoice', 'Fattura'), ('logo', 'Logo'), ('adv_material', 'Materiale ADV'), ('workshop_abstract', 'Abstract workshop'), ('compliance_aifa', 'Compliance AIFA'), ('stand_plan', 'Scheda stand'), ('event_floorplan', 'Planimetria evento'), ('other', 'Altro')], max_length=50, verbose_name='Tipo documento')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('storage_url', models.URLField(max_length=1000, verbose_name='URL storage')),
                ('storage_provider', models.CharField(choices=[('s3', 'AWS S3'), ('r2', 'Cloudflare R2'), ('local', 'Locale')], default='s3', max_length=20, verbose_name='Provider storage')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome file')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Dimensione (byte)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('version', models.IntegerField(default=1, verbose_name='Versione')),
                ('is_visible_to_sponsor', models.BooleanField(default=True, help_text='Se False, è un documento solo interno', verbose_name='Visibile a sponsor')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('code', models.CharField(help_text="Es. 'contract_initial_send', 'deadline_reminder_t10'", max_length=50, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('communication_type', models.CharField(choices=[('initial_send', 'Invio iniziale contratto'), ('reminder', 'Reminder scadenza'), ('overdue_alert', 'Sollecito ritardo'), ('thank_you', 'Ringraziamento'), ('document_request', 'Richiesta documenti'), ('manual', 'Manuale')], max_length=50, verbose_name='Tipo comunicazione')),
                ('subject_template', models.CharField(help_text='Supporta placeholder {{ var }}', max_length=500, verbose_name='Oggetto (template)')),
                ('body_template', models.TextField(help_text='Supporta placeholder {{ var }}', verbose_name='Corpo (template)')),
                ('language', models.CharField(default='it', max_length=2, verbose_name='Lingua')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Template email',
                'verbose_name_plural': 'Template email',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('export_type', models.CharField(choices=[('full', 'Totale'), ('deposit', 'Acconto'), ('balance', 'Saldo'), ('installment', 'Rata'), ('credit_note', 'Nota credito')], default='full', max_length=30, verbose_name='Tipo export')),
                ('installment_number', models.IntegerField(blank=True, null=True, verbose_name='Numero rata')),
                ('amount_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Imponibile')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale')),
                ('external_system', models.CharField(blank=True, help_text='Es. fattureincloud, aruba, fatel, manual', max_length=50, verbose_name='Sistema esterno')),
                ('external_invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Numero fattura esterna')),
                ('external_invoice_date', models.DateField(blank=True, null=True, verbose_name='Data fattura esterna')),
                ('external_reference_id', models.CharField(blank=True, max_length=100, verbose_name='ID riferimento esterno')),
                ('status', models.CharField(choices=[('pending_export', 'Da esportare'), ('exported', 'Esportato'), ('invoiced', 'Fatturato'), ('paid', 'Pagato'), ('cancelled', 'Annullato')], default='pending_export', max_length=20, verbose_name='Stato')),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal_data_snapshot', models.JSONField(help_text="Dati sponsor congelati al momento dell'export", verbose_name='Snapshot dati fiscali')),
                ('export_file_url', models.URLField(blank=True, max_length=500, verbose_name='URL file export')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Export fattura',
                'verbose_name_plural': 'Export fatture',
                'ordering': ['-created_at'],
            },
        ),
    ]
