# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contracts', '0003_initial'),
        ('shared', '0001_initial'),
        ('sponsors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo entità'),
        ),
        migrations.AddField(
            model_name='communication',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Inviata da utente'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo entità'),
        ),
        migrations.AddField(
            model_name='document',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='shared.document', verbose_name='Sostituito da'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='sponsors.contact', verbose_name='Caricato da contatto'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da utente'),
        ),
        migrations.AddField(
            model_name='invoiceexport',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_exports', to='contracts.contract', verbose_name='Contratto'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='shared_audi_entity__48f0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='shared_audi_user_id_69995f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='shared_audi_created_a7c60b_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['content_type', 'object_id'], name='shared_comm_content_a1ad8a_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status'], name='shared_comm_status_862483_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['provider_message_id'], name='shared_comm_provide_4a93ad_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='shared_docu_content_d9c288_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='shared_docu_documen_7a3fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceexport',
            index=models.Index(fields=['status'], name='shared_invo_status_f6545b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceexport',
            index=models.Index(fields=['external_invoice_number'], name='shared_invo_externa_525cd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceexport',
            constraint=models.UniqueConstraint(fields=('contract', 'export_type', 'installment_number'), name='invoice_export_unique_installment'),
        ),
    ]
