# Generated by Django 5.1.4 on 2026-05-25 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_document_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('name', models.CharField(help_text="Es. 'Preventivo iniziale', 'Rettifica', 'Invio documenti'", max_length=255, verbose_name='Nome')),
                ('body_template', models.TextField(help_text='Segnaposti: {{ azienda }}, {{ evento }}, {{ date_evento }}, {{ luogo_evento }}, {{ numero }}, {{ totale }}, {{ stand }}, {{ servizi }}', verbose_name='Corpo lettera (template)')),
                ('language', models.CharField(default='it', max_length=2, verbose_name='Lingua')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Template lettera',
                'verbose_name_plural': 'Template lettere',
                'ordering': ['name'],
            },
        ),
    ]
