# Generated by Django 5.1.4 on 2026-06-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0007_alter_document_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceexport",
            name="fiscal_data_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dati sponsor congelati al momento dell'export. Se vuoto, viene compilato in automatico dallo sponsor del contratto.",
                verbose_name="Snapshot dati fiscali",
            ),
        ),
    ]
