# Generated by Django 5.1.4 on 2026-06-10 07:19
# + conversione dati: i vecchi valori erano repr Python di dict ({'it': ...}),
#   JSON non valido. Vanno normalizzati a JSON valido PRIMA di alterare la
#   colonna a jsonb, altrimenti il cast text->jsonb fallisce.

import ast
import json

from django.db import migrations, models


def _to_json_text(val):
    """Normalizza un valore (repr Python / JSON / testo semplice) in una
    stringa JSON valida che rappresenta un dict {lingua: testo}."""
    if val is None or val == "":
        return json.dumps({})
    if isinstance(val, dict):
        return json.dumps(val, ensure_ascii=False)
    if isinstance(val, str):
        # 1) gia' JSON valido?
        try:
            d = json.loads(val)
            if isinstance(d, dict):
                return json.dumps(d, ensure_ascii=False)
            return json.dumps({"it": str(d)}, ensure_ascii=False)
        except (ValueError, TypeError):
            pass
        # 2) repr Python ({'it': '...'})?
        try:
            d = ast.literal_eval(val)
            if isinstance(d, dict):
                return json.dumps(d, ensure_ascii=False)
        except (ValueError, SyntaxError, TypeError):
            pass
        # 3) testo semplice -> mettilo come italiano
        return json.dumps({"it": val}, ensure_ascii=False)
    return json.dumps({"it": str(val)}, ensure_ascii=False)


def normalizza_a_json(apps, schema_editor):
    EmailTemplate = apps.get_model("shared", "EmailTemplate")
    for tpl in EmailTemplate.objects.all():
        tpl.subject_template = _to_json_text(tpl.subject_template)
        tpl.body_template = _to_json_text(tpl.body_template)
        tpl.save(update_fields=["subject_template", "body_template"])


def noop_reverse(apps, schema_editor):
    # Irreversibile a livello dati (dict -> stringa), ma la colonna tornerebbe
    # comunque text: non serve fare nulla.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0008_alter_invoiceexport_fiscal_data_snapshot"),
    ]

    operations = [
        # 1) prima sistemiamo il TESTO (colonna ancora char/text)
        migrations.RunPython(normalizza_a_json, noop_reverse),
        # 2) poi convertiamo la colonna a jsonb (il cast ora trova JSON valido)
        migrations.AlterField(
            model_name="emailtemplate",
            name="body_template",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Supporta placeholder {{ var }}",
                verbose_name="Corpo (template)",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="subject_template",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Supporta placeholder {{ var }}",
                verbose_name="Oggetto (template)",
            ),
        ),
    ]
