# Generated by Django 5.1.4 on 2026-06-10 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("shared", "0009_alter_emailtemplate_body_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Tipo entità",
            ),
        ),
        migrations.AlterField(
            model_name="communication",
            name="object_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="ID entità"),
        ),
    ]
