# Generated by Django 5.1.4 on 2026-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0010_alter_communication_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={
                "ordering": ["code", "event_type"],
                "verbose_name": "Template email",
                "verbose_name_plural": "Template email",
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[("", "Tutti gli eventi"), ("ECM", "ECM"), ("NON_ECM", "Non ECM")],
                default="",
                help_text="A quale tipo di evento si applica questo modello. 'Tutti gli eventi' = usato come default quando non c'e' un modello specifico per ECM o Non ECM.",
                max_length=20,
                verbose_name="Tipo evento",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="code",
            field=models.CharField(
                help_text="Identifica QUANDO parte l'email (es. 'deadline_reminder').",
                max_length=50,
                verbose_name="Punto di invio",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailtemplate",
            constraint=models.UniqueConstraint(
                fields=("code", "event_type"), name="uniq_emailtemplate_code_eventtype"
            ),
        ),
    ]
