# Generated by Django 5.1.4 on 2026-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0013_alter_document_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("contract_pdf", "Contratto PDF"),
                    ("quote", "Preventivo"),
                    ("admission_request", "Domanda di ammissione"),
                    ("contract_pdf_word", "Contratto (Word)"),
                    ("sponsor_contract_word", "Contratto sponsor (Word)"),
                    ("admission_request_word", "Domanda (Word)"),
                    ("client_summary", "Scheda cliente"),
                    ("signed_contract", "Contratto firmato"),
                    ("invoice", "Fattura"),
                    ("proforma", "Fattura proforma"),
                    ("proforma_acconto", "Fattura proforma (acconto)"),
                    ("proforma_saldo", "Fattura proforma (saldo)"),
                    ("logo", "Logo"),
                    ("adv_material", "Materiale ADV"),
                    ("workshop_abstract", "Abstract workshop"),
                    ("compliance_aifa", "Compliance AIFA"),
                    ("stand_plan", "Scheda stand"),
                    ("event_floorplan", "Planimetria evento"),
                    ("other", "Altro"),
                ],
                max_length=50,
                verbose_name="Tipo documento",
            ),
        ),
    ]
