# Generated by Django 5.1.4 on 2026-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0015_alter_communication_communication_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="communication_type",
            field=models.CharField(
                choices=[
                    ("initial_send", "Invio iniziale contratto"),
                    ("reminder", "Reminder scadenza"),
                    ("overdue_alert", "Sollecito ritardo"),
                    ("thank_you", "Ringraziamento"),
                    ("document_request", "Richiesta documenti"),
                    ("manual", "Manuale"),
                    ("promotional_campaign", "Campagna promozionale"),
                    ("proforma_generated", "Fattura proforma generata"),
                ],
                max_length=50,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="communication_type",
            field=models.CharField(
                choices=[
                    ("initial_send", "Invio iniziale contratto"),
                    ("reminder", "Reminder scadenza"),
                    ("overdue_alert", "Sollecito ritardo"),
                    ("thank_you", "Ringraziamento"),
                    ("document_request", "Richiesta documenti"),
                    ("manual", "Manuale"),
                    ("promotional_campaign", "Campagna promozionale"),
                    ("proforma_generated", "Fattura proforma generata"),
                ],
                max_length=50,
                verbose_name="Tipo comunicazione",
            ),
        ),
    ]
