# Generated by Django 5.1.4 on 2026-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_alter_communication_communication_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='communication_type',
            field=models.CharField(choices=[('initial_send', 'Invio iniziale contratto'), ('reminder', 'Reminder scadenza'), ('overdue_alert', 'Sollecito ritardo'), ('thank_you', 'Ringraziamento'), ('document_request', 'Richiesta documenti'), ('manual', 'Manuale'), ('promotional_campaign', 'Campagna promozionale'), ('proforma_generated', 'Fattura proforma generata'), ('pass_allestimento', 'PASS allestimento')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='communication_type',
            field=models.CharField(choices=[('initial_send', 'Invio iniziale contratto'), ('reminder', 'Reminder scadenza'), ('overdue_alert', 'Sollecito ritardo'), ('thank_you', 'Ringraziamento'), ('document_request', 'Richiesta documenti'), ('manual', 'Manuale'), ('promotional_campaign', 'Campagna promozionale'), ('proforma_generated', 'Fattura proforma generata'), ('pass_allestimento', 'PASS allestimento')], max_length=50, verbose_name='Tipo comunicazione'),
        ),
    ]
