# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Ruolo aziendale')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('signer', 'Firmatario'), ('marketing', 'Marketing'), ('finance', 'Amministrazione'), ('operational', 'Operativo'), ('cc', 'CC')], max_length=20), blank=True, default=list, help_text='Determina chi riceve quali comunicazioni', size=None, verbose_name='Ruoli funzionali')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contatto principale')),
                ('marketing_consent', models.BooleanField(default=False, help_text='Per newsletter promozionali oltre alle comunicazioni transazionali', verbose_name='Consenso marketing')),
                ('preferred_language', models.CharField(default='it', help_text='Usata per email automatiche e UI portale', max_length=2, verbose_name='Lingua preferita')),
                ('has_portal_access', models.BooleanField(default=False, help_text='Se True, può autenticarsi nel portale sponsor self-service', verbose_name='Accesso portale')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('is_signer', models.BooleanField(default=False, help_text='Se True, può firmare i contratti per conto dello sponsor', verbose_name='È il legale rappresentante firmatario?')),
                ('signer_tax_code', models.CharField(blank=True, help_text='Solo se is_signer=True. Es. RSSMRA75C15H501Z', max_length=16, verbose_name='Codice Fiscale (persona fisica)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='Luogo di nascita')),
                ('birth_province', models.CharField(blank=True, max_length=2, verbose_name='Provincia nascita')),
                ('residence_street', models.CharField(blank=True, max_length=255, verbose_name='Via residenza')),
                ('residence_street_number', models.CharField(blank=True, max_length=10, verbose_name='Civico residenza')),
                ('residence_city', models.CharField(blank=True, max_length=100, verbose_name='Città residenza')),
                ('residence_zip', models.CharField(blank=True, max_length=10, verbose_name='CAP residenza')),
                ('residence_province', models.CharField(blank=True, max_length=2, verbose_name='Provincia residenza')),
                ('id_document_type', models.CharField(blank=True, choices=[('CI', "Carta d'Identità"), ('PA', 'Passaporto'), ('PG', 'Patente di Guida')], default='CI', max_length=2, verbose_name='Tipo documento')),
                ('id_document_number', models.CharField(blank=True, max_length=20, verbose_name='Numero documento')),
            ],
            options={
                'verbose_name': 'Contatto',
                'verbose_name_plural': 'Contatti',
                'ordering': ['sponsor', '-is_primary', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancellato il')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Ragione sociale')),
                ('display_name', models.CharField(blank=True, help_text="Nome breve, es. 'MedNova' invece di 'MedNova Italia S.r.l.'", max_length=255, verbose_name='Nome commerciale')),
                ('vat_number', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Partita IVA')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Codice fiscale')),
                ('sdi_code', models.CharField(blank=True, help_text='Per fatturazione elettronica', max_length=7, verbose_name='Codice destinatario SDI')),
                ('pec_email', models.EmailField(blank=True, max_length=254, verbose_name='PEC')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('address_zip', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('address_province', models.CharField(blank=True, max_length=2, verbose_name='Provincia')),
                ('address_country', models.CharField(default='IT', help_text='Codice ISO 3166-1 alpha-2 (es. IT, FR, DE)', max_length=2, verbose_name='Paese')),
                ('requires_aifa', models.BooleanField(default=False, verbose_name='Richiede AIFA')),
                ('requires_svc_medtech', models.BooleanField(default=False, verbose_name='Richiede SVC MedTech')),
                ('rea_city', models.CharField(blank=True, help_text="Città del Registro Imprese (es. 'Bologna')", max_length=100, verbose_name='Città REA')),
                ('rea_number', models.CharField(blank=True, help_text="Es. 'BO252016'", max_length=20, verbose_name='Numero REA')),
                ('business_description', models.CharField(blank=True, help_text="Es. 'prodotti farmaceutici per uso umano' (usato nei contratti)", max_length=255, verbose_name='Descrizione attività')),
                ('industry', models.CharField(blank=True, help_text='Es. pharma, medtech, diagnostics', max_length=50, verbose_name='Settore')),
                ('website', models.URLField(blank=True, verbose_name='Sito web')),
                ('logo_url', models.URLField(blank=True, help_text='URL su S3/storage del logo aziendale', max_length=500, verbose_name='URL logo')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsor',
                'ordering': ['legal_name'],
            },
        ),
    ]
