# Generated by Django 5.1.4 on 2026-05-07 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='portal_user',
            field=models.OneToOneField(blank=True, help_text='Account User per login al portale (se has_portal_access=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utente portale collegato'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['legal_name'], name='sponsors_sp_legal_n_b0cb76_idx'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sponsors.sponsor', verbose_name='Sponsor'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='sponsors_co_email_9feb93_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['roles'], name='idx_contact_roles_gin'),
        ),
    ]
