# Generated by Django 5.1.4 on 2026-05-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancellato il'),
        ),
    ]
