# Generated by Django 5.1.4 on 2026-05-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_contact_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='requires_aifa',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='requires_svc_medtech',
        ),
    ]
