# Generated by Django 5.1.4 on 2026-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_remove_sponsor_requires_aifa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo_file',
            field=models.ImageField(blank=True, help_text="Immagine caricata dal cliente; ha priorita' sull'URL.", null=True, upload_to='sponsor_logos/', verbose_name='Logo (file caricato)'),
        ),
    ]
