# Generated by Django 5.1.4 on 2026-05-28 20:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_sponsor_logo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('signer', 'Firmatario'), ('marketing', 'Marketing'), ('finance', 'Amministrazione'), ('operational', 'Operativo'), ('cc', 'CC'), ('educational', 'Educational manager')], max_length=20), blank=True, default=list, help_text='Determina chi riceve quali comunicazioni', size=None, verbose_name='Ruoli funzionali'),
        ),
    ]
