# Generated by Django 5.1.4 on 2026-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_alter_contact_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='portal_message',
            field=models.TextField(blank=True, default='', help_text='Mostrato a questo sponsor nella home del portale.', verbose_name='Messaggio in evidenza (portale)'),
        ),
    ]
