# Generated by Django 5.1.4 on 2026-06-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0007_sponsor_portal_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['sponsor', '-is_primary', 'full_name'], 'verbose_name': 'Anagrafica di riferimento', 'verbose_name_plural': 'Anagrafica di riferimento'},
        ),
    ]
