# Generated by Django 5.1.4 on 2026-06-06 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_venue_name"),
        ("sponsors", "0008_alter_contact_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modificato il")),
                ("body", models.TextField(verbose_name="Messaggio")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se disattivato non compare nel portale.",
                        verbose_name="Attivo",
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="Letto il")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_portal_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inviato da",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lascia vuoto per un messaggio generico.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_messages",
                        to="events.event",
                        verbose_name="Evento (opzionale)",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_portal_messages",
                        to="sponsors.contact",
                        verbose_name="Letto da",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_messages",
                        to="sponsors.sponsor",
                        verbose_name="Sponsor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio portale",
                "verbose_name_plural": "Messaggi portale",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sponsor", "read_at"], name="sponsors_po_sponsor_e1ae36_idx"
                    )
                ],
            },
        ),
    ]
