# Generated by Django 5.1.4 on 2026-06-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0010_migra_portal_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalmessage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Vuoto = nuovo messaggio; valorizzato = risposta nel thread.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="sponsors.portalmessage",
                verbose_name="In risposta a",
            ),
        ),
        migrations.AddField(
            model_name="portalmessage",
            name="sender",
            field=models.CharField(
                choices=[("operator", "Operatore"), ("sponsor", "Sponsor")],
                default="operator",
                max_length=20,
                verbose_name="Da",
            ),
        ),
    ]
