# Generated by Django 5.1.4 on 2026-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0011_portalmessage_parent_portalmessage_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="marketing_consent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Consenso marketing il"),
        ),
        migrations.AddField(
            model_name="contact",
            name="privacy_accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Informativa privacy accettata il"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="privacy_policy_version",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Versione informativa accettata"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="marketing_consent",
            field=models.BooleanField(
                default=False, verbose_name="Consenso comunicazioni marketing"
            ),
        ),
    ]
