# Generated by Django 5.1.4 on 2026-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0012_contact_marketing_consent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalmessage",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Messaggi archiviati: spostati nell'archivio, fuori dall'inbox attiva.",
                null=True,
                verbose_name="Archiviato il",
            ),
        ),
    ]
