# Generated by Django 5.1.4 on 2026-06-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0013_portalmessage_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="Nome"),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="Cognome"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Compilato in automatico da Nome + Cognome.",
                max_length=255,
                verbose_name="Nome completo",
            ),
        ),
    ]
