# Generated by Django 5.1.4 on 2026-07-03 17:52

from django.db import migrations, models
from django.utils import timezone


def marca_esistenti_come_visto(apps, schema_editor):
    """I contatti gia' presenti non devono vedere il benvenuto di primo accesso:
    li marco tutti come gia' visti. Solo i contatti creati DOPO questa migration
    (nuovi utenti) avranno welcome_seen_at NULL e vedranno il messaggio."""
    Contact = apps.get_model("sponsors", "Contact")
    Contact.objects.filter(welcome_seen_at__isnull=True).update(
        welcome_seen_at=timezone.now()
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0015_split_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="welcome_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Benvenuto portale visto il"
            ),
        ),
        migrations.RunPython(marca_esistenti_come_visto, noop),
    ]
