# Generated by Django 5.1.4 on 2026-07-06 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0016_contact_welcome_seen_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="portal_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Account User per login al portale (se has_portal_access=True). Lo stesso utente puo' essere collegato a contatti di piu' aziende.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_profiles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utente portale collegato",
            ),
        ),
    ]
