# Generated by Django 5.1.4 on 2026-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0017_alter_contact_portal_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="is_pharma_company",
            field=models.BooleanField(
                default=False,
                help_text="Se sì, è richiesto il Codice SIS",
                verbose_name="Azienda farmaceutica",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="sis_code",
            field=models.CharField(
                blank=True,
                help_text="Codice identificativo SIS (solo aziende farmaceutiche)",
                max_length=20,
                verbose_name="Codice SIS",
            ),
        ),
    ]
