# Generated by Django 5.1.4 on 2026-07-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0018_sponsor_is_pharma_company_sponsor_sis_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="business_description",
            field=models.CharField(
                blank=True,
                help_text="Es. 'prodotti farmaceutici per uso umano' (usato nei contratti)",
                max_length=5000,
                verbose_name="Descrizione attività",
            ),
        ),
    ]
