# Generated by Django 5.1.4 on 2026-10-07 23:18

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0019_alter_sponsor_business_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="left_company_at",
            field=models.DateField(
                blank=True,
                help_text="Valorizzato dal trasferimento ad altra azienda: il contatto resta per lo storico dei contratti ma non riceve più comunicazioni.",
                null=True,
                verbose_name="Non più in azienda dal",
            ),
        ),
        migrations.CreateModel(
            name="InterestArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modificato il")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Le aree disattivate non compaiono nelle nuove selezioni.",
                        verbose_name="Attiva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area di interesse",
                "verbose_name_plural": "Aree di interesse",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_interestarea_name_ci",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="interest_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tipologie di evento che segue QUESTA persona.",
                related_name="contacts",
                to="sponsors.interestarea",
                verbose_name="Aree di interesse",
            ),
        ),
        migrations.CreateModel(
            name="InterestCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modificato il")),
                (
                    "name",
                    models.CharField(
                        help_text="Solo per riconoscerla in lista: il cliente non la vede.",
                        max_length=255,
                        verbose_name="Nome interno",
                    ),
                ),
                ("subject", models.JSONField(blank=True, default=dict, verbose_name="Oggetto")),
                (
                    "body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Segnaposto: {{ contact.first_name }}, {{ contact.full_name }}, {{ sponsor.legal_name }}.",
                        verbose_name="Corpo email",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Inviata il")),
                (
                    "sent_count",
                    models.PositiveIntegerField(default=0, verbose_name="Email inviate"),
                ),
                (
                    "interest_areas",
                    models.ManyToManyField(
                        help_text="Riceve chi segue ALMENO UNA delle aree scelte.",
                        related_name="campaigns",
                        to="sponsors.interestarea",
                        verbose_name="Aree di interesse",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inviata da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagna per aree di interesse",
                "verbose_name_plural": "Campagne per aree di interesse",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuppressedEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modificato il")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsubscribed", "Disiscritto dal marketing"),
                            ("anonymized", "Dati cancellati (GDPR)"),
                        ],
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email esclusa dal marketing",
                "verbose_name_plural": "Email escluse dal marketing",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="unique_suppressedemail_email_ci",
                    )
                ],
            },
        ),
    ]
