# Generated by Django 5.1.4 on 2026-10-08 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0020_rubrica"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="transferred_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Scheda della stessa persona nell'azienda precedente: la cancellazione GDPR segue tutta la catena, anche se l'email è cambiata.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferred_to",
                to="sponsors.contact",
                verbose_name="Trasferito da",
            ),
        ),
    ]
