# Generated by Django 5.1.4 on 2026-05-07 10:55

import core.translatable
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('code', models.CharField(help_text='Es. WORKSHOP_30MIN, HOSTESS_DAY', max_length=50, verbose_name='Codice')),
                ('name', models.JSONField(help_text='Formato: {"it": "...", "en": "..."}', verbose_name='Nome (multilingua)')),
                ('description', models.JSONField(blank=True, null=True, verbose_name='Descrizione (multilingua)')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Categoria')),
                ('accounting_category', models.CharField(choices=[('viaggio_partecipanti', 'Viaggio/ospitalità partecipanti'), ('viaggio_relatori', 'Viaggio/ospitalità relatori'), ('affitto_sala', 'Affitto sala'), ('stand', 'Spazi espositivi/stand'), ('coffee_break', 'Coffee break/colazioni'), ('scheda_tecnica', 'Scheda tecnica/cartella'), ('quota_iscrizione', "Quota d'iscrizione"), ('altro', 'Altre spese')], default='altro', help_text="Per raggruppamento nell'allegato 2 dei contratti ECM", max_length=30, verbose_name='Categoria contabile')),
                ('pricing_mode', models.CharField(choices=[('fixed', 'Prezzo fisso'), ('quantity', 'Per quantità'), ('tiered', 'Scaglioni')], default='fixed', max_length=20, verbose_name='Modalità pricing')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prezzo base')),
                ('pricing_tiers', models.JSONField(blank=True, null=True, verbose_name='Scaglioni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('max_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantità massima')),
                ('triggers_deadlines', models.BooleanField(default=False, verbose_name='Genera scadenze')),
                ('is_self_purchasable', models.BooleanField(default=False, help_text='Se True, appare nel portale ecommerce per gli sponsor', verbose_name='Acquistabile self-service')),
                ('self_purchase_cutoff_days', models.IntegerField(blank=True, help_text="Giorni minimi prima dell'evento per poter ancora acquistare. NULL = nessun cutoff. 0 = acquistabile il giorno stesso. Es. 14 = chiude 14 giorni prima dell'evento.", null=True, verbose_name='Cutoff acquisto (gg prima evento)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=4, verbose_name='Aliquota IVA (%)')),
                ('vat_exemption_article', models.CharField(blank=True, max_length=100, verbose_name='Articolo esenzione IVA')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine visualizzazione')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['event', 'display_order'],
            },
            bases=(core.translatable.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeadlineTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deadline_type', models.CharField(max_length=50, verbose_name='Tipo scadenza')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('days_before_event', models.IntegerField(verbose_name="Giorni prima dell'evento")),
                ('notify_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None, verbose_name='Ruoli da notificare')),
                ('reminder_days_before', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, verbose_name='Reminder a (giorni prima)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_templates', to='catalog.service', verbose_name='Servizio')),
            ],
            options={
                'verbose_name': 'Template scadenza',
                'verbose_name_plural': 'Template scadenze',
                'ordering': ['service', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='catalog_ser_categor_872480_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_self_purchasable', 'is_active'], name='catalog_ser_is_self_456303_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='service_code_unique_per_event'),
        ),
    ]
