# Generated by Django 5.1.4 on 2026-05-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, help_text="Foto dell'articolo mostrata nel catalogo.", null=True, upload_to='services/images/', verbose_name='Immagine'),
        ),
    ]
