# Generated by Django 5.1.4 on 2026-05-24 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_available',
            field=models.IntegerField(blank=True, help_text='Quanti pezzi esistono in totale (es. 1 per uno stand unico). Vuoto = illimitato.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantità totale disponibile'),
        ),
    ]
