# Generated by Django 5.1.4 on 2026-05-29 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_total_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinetemplate',
            name='submission_kind',
            field=models.CharField(choices=[('file', 'Solo file'), ('content', 'Solo campi da compilare'), ('both', 'File + campi da compilare')], default='file', help_text='File, campi da compilare, oppure entrambi.', max_length=20, verbose_name='Cosa deve fornire il cliente'),
        ),
        migrations.CreateModel(
            name='DeadlineFieldTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('label', models.CharField(max_length=255, verbose_name='Etichetta')),
                ('key', models.SlugField(blank=True, help_text="Lasciare vuoto: viene generata dall'etichetta.", max_length=60, verbose_name='Chiave')),
                ('field_type', models.CharField(choices=[('short_text', 'Testo breve'), ('long_text', 'Testo lungo')], default='short_text', max_length=20, verbose_name='Tipo')),
                ('required', models.BooleanField(default=True, verbose_name='Obbligatorio')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Testo di aiuto')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('deadline_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_fields', to='catalog.deadlinetemplate', verbose_name='Richiesta')),
            ],
            options={
                'verbose_name': 'Campo da compilare',
                'verbose_name_plural': 'Campi da compilare',
                'ordering': ['deadline_template', 'display_order'],
            },
        ),
    ]
