# Generated by Django 5.1.4 on 2026-05-30 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_deadlinetemplate_submission_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('label', models.CharField(help_text='Es. Rosso, Taglia L, ...', max_length=120, verbose_name='Variante')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Codice')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prezzo di questa variante (sostituisce il prezzo base del servizio).', max_digits=10, verbose_name='Prezzo variante')),
                ('total_available', models.IntegerField(blank=True, help_text="Quantita' disponibile di questa variante. Vuoto = illimitate.", null=True, verbose_name='Scorte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.service', verbose_name='Servizio')),
            ],
            options={
                'verbose_name': 'Variante servizio',
                'verbose_name_plural': 'Varianti servizio',
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
