# Generated by Django 5.1.4 on 2026-06-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_servicevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='included_services',
            field=models.ManyToManyField(blank=True, help_text='Servizi aggiunti automaticamente a € 0 quando questo servizio viene venduto. Le loro scadenze materiali si generano alla firma.', related_name='included_in', to='catalog.service', verbose_name='Servizi inclusi (accessori)'),
        ),
    ]
