# Generated by Django 5.1.4 on 2026-06-04 06:33

import core.translatable
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_service_included_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codice')),
                ('name', models.JSONField(help_text='Formato: {"it": "...", "en": "..."}', verbose_name='Nome (multilingua)')),
                ('description', models.JSONField(blank=True, null=True, verbose_name='Descrizione (multilingua)')),
                ('image', models.FileField(blank=True, null=True, upload_to='catalog/images/', verbose_name='Immagine')),
                ('accounting_category', models.CharField(choices=[('viaggio_partecipanti', 'Viaggio/ospitalità partecipanti'), ('viaggio_relatori', 'Viaggio/ospitalità relatori'), ('affitto_sala', 'Affitto sala'), ('stand', 'Spazi espositivi/stand'), ('coffee_break', 'Coffee break/colazioni'), ('scheda_tecnica', 'Scheda tecnica/cartella'), ('quota_iscrizione', "Quota d'iscrizione"), ('altro', 'Altre spese')], default='altro', max_length=30, verbose_name='Categoria contabile')),
                ('pricing_mode', models.CharField(choices=[('fixed', 'Prezzo fisso'), ('quantity', 'Per quantità'), ('tiered', 'Scaglioni')], default='fixed', max_length=20, verbose_name='Modalità pricing')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prezzo base (default)')),
                ('pricing_tiers', models.JSONField(blank=True, null=True, verbose_name='Scaglioni')),
                ('max_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantità massima')),
                ('triggers_deadlines', models.BooleanField(default=False, verbose_name='Genera scadenze')),
                ('is_self_purchasable', models.BooleanField(default=False, verbose_name='Acquistabile self-service')),
                ('self_purchase_cutoff_days', models.IntegerField(blank=True, null=True, verbose_name='Cutoff acquisto (gg prima evento)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=4, verbose_name='Aliquota IVA (%)')),
                ('vat_exemption_article', models.CharField(blank=True, max_length=100, verbose_name='Articolo esenzione IVA')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine visualizzazione')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Servizio a catalogo',
                'verbose_name_plural': 'Catalogo servizi',
                'ordering': ['display_order', 'code'],
            },
            bases=(core.translatable.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('code', models.SlugField(unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=80, verbose_name='Nome categoria')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Categoria servizio',
                'verbose_name_plural': 'Categorie servizio (catalogo)',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='catalog_source',
            field=models.ForeignKey(blank=True, help_text='Se valorizzato, il servizio nasce da una voce del catalogo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='catalog.catalogservice', verbose_name='Origine (catalogo)'),
        ),
        migrations.CreateModel(
            name='CatalogServiceVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('label', models.CharField(max_length=120, verbose_name='Variante')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Codice')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo variante')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('catalog_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.catalogservice', verbose_name='Servizio a catalogo')),
            ],
            options={
                'verbose_name': 'Variante (catalogo)',
                'verbose_name_plural': 'Varianti (catalogo)',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_services', to='catalog.servicecategory', verbose_name='Categoria'),
        ),
    ]
