# Generated by Django 5.1.4 on 2026-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_catalogservice_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogservicevariant',
            name='label_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Etichetta (EN)'),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='label_en',
            field=models.CharField(blank=True, help_text="Traduzione inglese. Vuoto = usa l'italiano.", max_length=120, verbose_name='Etichetta (EN)'),
        ),
    ]
