# Generated by Django 5.1.4 on 2026-06-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_serviceinclusion_quantita"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadlinetemplate",
            name="client_template_file",
            field=models.FileField(
                blank=True,
                help_text="Facoltativo. File di traccia che il cliente scarica per preparare il materiale richiesto: es. un template grafico alla misura giusta, oppure un Excel con le colonne/info da compilare.",
                null=True,
                upload_to="deadline_templates/",
                verbose_name="Modello da far scaricare al cliente",
            ),
        ),
    ]
