# Generated by Django 5.1.4 on 2026-06-10 16:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_deadlinetemplate_client_template_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deadlinetemplate",
            name="days_before_event",
            field=models.IntegerField(
                help_text="Quando cade la scadenza: tot giorni prima dell'inizio evento. Es. 30 = la scadenza è 30 giorni prima dell'evento.",
                verbose_name="Giorni prima dell'evento",
            ),
        ),
        migrations.AlterField(
            model_name="deadlinetemplate",
            name="reminder_days_before",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="Quanti giorni PRIMA DELLA SCADENZA inviare i promemoria. Puoi metterne più di uno separati da virgola, es. 15, 7, 3 (tre promemoria, a 15-7-3 giorni dalla scadenza). Vuoto = nessun reminder automatico.",
                size=None,
                verbose_name="Reminder a (giorni prima della scadenza)",
            ),
        ),
    ]
