# Generated by Django 5.1.4 on 2026-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_deadlinetemplate_days_before_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadlinetemplate",
            name="shipping_instructions",
            field=models.TextField(
                blank=True,
                help_text="Visibile al cliente nel portale quando il tipo è 'Materiale fisico'. Indica indirizzo di spedizione, imballo, riferimento da riportare, ecc.",
                verbose_name="Istruzioni di spedizione",
            ),
        ),
        migrations.AlterField(
            model_name="deadlinetemplate",
            name="submission_kind",
            field=models.CharField(
                choices=[
                    ("file", "Solo file"),
                    ("content", "Solo campi da compilare"),
                    ("both", "File + campi da compilare"),
                    ("physical", "Materiale fisico (spedizione postale)"),
                ],
                default="file",
                help_text="File, campi da compilare, oppure entrambi.",
                max_length=20,
                verbose_name="Cosa deve fornire il cliente",
            ),
        ),
    ]
