# Generated by Django 5.1.4 on 2026-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_deadline_template_physical_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadlinetemplate",
            name="file_area_label",
            field=models.CharField(
                blank=True,
                help_text="Testo mostrato DENTRO il riquadro di caricamento file nel portale (es. '📎 Dichiarazione del medico in PDF'). Vuoto = riquadro generico.",
                max_length=255,
                verbose_name="Etichetta area di caricamento",
            ),
        ),
    ]
