# Generated by Django 5.1.4 on 2026-09-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_deadlinetemplate_file_area_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceinclusion',
            options={'ordering': ['id'], 'verbose_name': 'Servizio incluso', 'verbose_name_plural': 'Servizi inclusi'},
        ),
    ]
