# Generated by Django 5.1.4 on 2026-10-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_serviceinclusion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinetemplate',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(blank=True, help_text="Limite per ogni file caricato dal cliente. Vuoto = 20 MB. Per le grafiche di stampa (es. banner) si puo' alzare, es. 100.", null=True, verbose_name='Dimensione massima file (MB)'),
        ),
    ]
